"use client";

import React from "react";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

export default function TermsOfUsePage() {
    return (
        <main className="min-h-screen bg-white">
            <Header />

            {/* Spacer for fixed header */}
            <div className="h-[85px]"></div>

            <section className="max-w-[1000px] mx-auto px-6 lg:px-8 py-16 lg:py-24">
                <h1 className="font-heading text-[42px] lg:text-[52px] font-bold text-[#161c2d] mb-8 tracking-[-1px]">
                    Terms Of Use
                </h1>

                <div className="font-body text-[16px] text-[#161c2d] leading-relaxed space-y-8">
                    {/* Metadata */}
                    <div className="mb-8">
                        <p><strong>Effective Date:</strong> January 26, 2026</p>
                    </div>

                    {/* 1. Agreement to Terms */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">1. Agreement to Terms</h2>
                        <p>
                            These Terms constitute a legally binding agreement between you ("User") and Xapien Innovatus Private Limited (CIN: U62090KL2025PTC092495). By accessing tucknow.com, interacting with a Tuck Magic Mirror, or using the Tuck API, you accept these Terms.
                        </p>
                    </div>

                    {/* 2. License Grant */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">2. License Grant</h2>
                        <ul className="list-none space-y-4">
                            <li>
                                <strong>A. For End Users (Shoppers/Consumers):</strong> We grant you a limited, non-exclusive, revocable, non-transferable license to use the generated VTON images and Fit Recommendations for your personal, non-commercial use (e.g., purchase decisions, social sharing). You may NOT sell, license, or commercially distribute these images.
                            </li>
                            <li>
                                <strong>B. For Retail Partners (B2B Clients):</strong> If you are a retailer or business entity using Tuck services, your rights to commercialize the VTON technology and data are governed exclusively by the separate Master Services Agreement (MSA) or Commercial SaaS Agreement executed between you and Xapien Innovatus Private Limited.
                            </li>
                        </ul>
                    </div>

                    {/* 3. See Your Fit & Liability Disclaimer */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">3. "See Your Fit" & Liability Disclaimer (Global Shield)</h2>
                        <p className="font-bold mb-4">IMPORTANT: LIMITATION OF LIABILITY FOR SIZING ADVICE</p>
                        <p className="mb-4">The "See Your Fit" feature uses AI to estimate body measurements, generate heatmaps, and suggest sizes.</p>
                        <ul className="list-disc pl-5 space-y-2 mb-4">
                            <li><strong>Estimates Only:</strong> These are indicative suggestions generated by AI, not professional tailoring advice.</li>
                            <li><strong>Input Dependency:</strong> Accuracy depends entirely on the quality of the image and the accuracy of the height/gender inputs provided by you. A wrong height entry will result in incorrect body measurements.</li>
                            <li><strong>No Liability:</strong> To the fullest extent permitted by law, Xapien Innovatus Private Limited, its promoters, directors, and employees expressly disclaim liability for:</li>
                        </ul>
                        <ul className="list-disc pl-10 space-y-2">
                            <li>Inaccurate size recommendations, body measurements, or heatmaps.</li>
                            <li>Ill-fitting physical garments purchased based on these recommendations.</li>
                            <li>Return shipping costs, restocking fees, refunds, or exchanges.</li>
                        </ul>
                    </div>

                    {/* 4. User Conduct & Content */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">4. User Conduct & Content</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Prohibited Uploads:</strong> You agree NOT to upload nudity, sexually explicit content, offensive material, or third-party images without consent.</li>
                            <li><strong>Indemnity:</strong> You agree to defend, indemnify, and hold harmless Xapien Innovatus Private Limited from any claims, damages, or legal fees arising from your violation of these Terms or strict liability regarding the content you upload.</li>
                        </ul>
                    </div>

                    {/* 5. Limitation of Liability */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">5. Limitation of Liability</h2>
                        <p className="mb-4">To the maximum extent permitted by applicable law (including the Indian Contract Act, 1872):</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>No Consequential Damages:</strong> We are not liable for any indirect, special, incidental, or consequential damages (including loss of profit, data, or goodwill).</li>
                            <li><strong>"As Is" Basis:</strong> We do not guarantee 100% uptime or error-free AI generation. No Service Level Agreement (SLA) applies to standard End User accounts.</li>
                            <li><strong>Monetary Cap:</strong> Our total cumulative liability for any claim arising out of these Terms shall not exceed INR 1,000 (Indian Rupees One Thousand) or the amount paid by you for the specific transaction, whichever is lower.</li>
                        </ul>
                    </div>

                    {/* 6. Intellectual Property */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">6. Intellectual Property</h2>
                        <p>
                            All software, AI models, algorithms, UI designs, and the "Tuck" trademark are the exclusive property of Xapien Innovatus Private Limited.
                        </p>
                    </div>

                    {/* 7. Governing Law & Dispute Resolution */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">7. Governing Law & Dispute Resolution</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Governing Law:</strong> These Terms are governed by the laws of India.</li>
                            <li><strong>Exclusive Jurisdiction:</strong> You expressly agree that any legal claim or dispute arising out of or related to these Terms shall be instituted exclusively in the Courts at Ernakulam (Kochi), Kerala, India.</li>
                            <li><strong>Arbitration:</strong> We reserve the right to refer disputes to arbitration in Kochi under the Arbitration and Conciliation Act, 1996.</li>
                        </ul>
                    </div>

                    {/* 8. Contact Information */}
                    <div>
                        <h2 className="font-heading text-[20px] font-bold mb-4">8. Contact Information</h2>
                        <ul className="list-none pl-4 space-y-2">
                            <li>Xapien Innovatus Private Limited</li>
                            <li><strong>Email:</strong> <a href="mailto:info@xapien.in" className="text-blue-600 underline">info@xapien.in</a></li>
                            <li><strong>Phone:</strong> +91 8136926111</li>
                        </ul>
                    </div>
                </div>
            </section>

            <Footer showCta={false} />
        </main>
    );
}
